model:
  vit_base: ViT-B-16
  pretrained: openai
  # pretrained: /home/chuyu/vllab/clip/outputs/ViT-B-16/eurosat/20231212160959/checkpoint_10.pth
  use_pure_clip: False
  freeze_classification_head: True
  method:
    name: random_kd
    params:
      batch_size: 32
      ratio: 0.2
data:
  name: flowers-102
  root: /mnt/data/classification
  split:
    train:
      split_name: train
      batch_size: 32
      shuffle: True
      drop_last: True
    val:
      split_name: val
      batch_size: 256
      shuffle: False
      drop_last: False
    test:
      split_name: test
      batch_size: 256
      shuffle: False
      drop_last: False

task:
  # fine-tuning arguments
  init_lrs: 0.00001
  weight_decay: 0.0005
  seed: 1102
  max_epoch: 10
  warmup_length: 0

  output_dir: "outputs"
  log_interval: 10
