model:
  vit_base: ViT-B-16
  # pretrained: laion2b_s34b_b88k
  # pretrained: datacomp_xl_s13b_b90k
  pretrained: openai
data:
  name: flowers-102
  root: /mnt/data/classification
  split:
    train:
      split_name: train
      batch_size: 32
      shuffle: True
      drop_last: True
    val:
      split_name: val
      batch_size: 256
      shuffle: False
      drop_last: False
    test:
      split_name: test
      batch_size: 256
      shuffle: False
      drop_last: False

task:
  # fine-tuning arguments
  init_lrs: 0.00001
  weight_decay: 0.0005
  seed: 1102
  max_epoch: 10
  warmup_length: 0

  output_dir: "outputs"
  log_interval: 10
