model:
  vit_base: ViT-B-16
  pretrained: openai
  use_pure_clip: False
  freeze_classification_head: True
  wise:
    enable: False
    path: openai
    ratio: 0.2
data:
  name: fgvc-aircraft
  root: /mnt/data/classification
  split:
    test:
      split_name: test
      batch_size: 256
      shuffle: False
      drop_last: False
  inference_dataset_list:
    - fgvc-aircraft
    - caltech-101
    - dtd
    - eurosat
    - flowers-102
    - oxford-pets
    - stanford-cars
    - ucf-101

task:
  seed: 1102
